### ISSUE TITLE
unable to install gem

### ISSUE THREAD

**Issue by EricSlick** [ruby2d/ruby2d#2]
getting an error when compiling native extensions.

I'm using rvm and brew was installed by rvm, so I'm suspicious that this may be an issue related to a non-standard install of brew.

it's unable to include simple2d.h which I do have installed, so it's probably just unable to find the header file as it's in a non-standard location...at least that's my suspicion.

Here's the full dump of the error...

```console
$ gem install ruby2d
Building native extensions.  This could take a while...
ERROR:  Error installing ruby2d:
	ERROR: Failed to build gem native extension.

    /Users/ericslick/.rvm/rubies/ruby-2.2.4/bin/ruby -r ./siteconf20160103-78885-t55gek.rb extconf.rb
Cloning into '/Users/ericslick/.homebrew/Library/Taps/simple2d/homebrew-tap'...
Error: simple2d/tap/simple2d 0.0.4 already installed
creating Makefile

make "DESTDIR=" clean

make "DESTDIR="
compiling ruby2d.c
ruby2d.c:2:10: fatal error: 'simple2d.h' file not found
#include <simple2d.h>
         ^
1 error generated.
make: *** [ruby2d.o] Error 1

make failed, exit code 2
```

I was interested in your library as it seemed to be a newer project, the graphics I need to do are plenty simple enough for what's implemented and it's not a production project,. I simply need to visualize something pretty basic (lots of little bocks).

**Comment by blacktm** [comment]
Hi @EricSlick. A few things to try. First, I pushed a new version of Simple 2D, so you could try updating (`brew update && brew upgrade simple2d`) and reinstall the gem. You can test if Ruby can find the header and library using:

```ruby
require 'mkmf'
have_header('simple2d.h')
have_library('simple2d')
```

If it can't, it's probably because of the location Homebrew is installed, a `PATH` issue – they are pretty insistent on [installing in `/usr/local`](https://github.com/Homebrew/homebrew/blob/master/share/doc/homebrew/FAQ.md#why-does-homebrew-insist-i-install-to-usrlocal). Good luck!

**Comment by EricSlick** [comment]
Thanks, that did the trick. It's bundling now.

**Comment by EricSlick** [comment]
Unfortunately, I closed this too soon.  

It's working fine on my iMac, but is still failing on my Macbook Pro

There must be something different about the environments, but so far I confirmed the two are using the same PATHS, ruby, brew (located in the same path), simple2d (also located in the same path), updated

I tried rebuilding from "scratch (ish)", to ensure pathing wasn't an issue. However, it still fails in the same way. I dropped rvm, used rbenv, tried the latest ruby and the one I current use on my iMac (for both).

I installed nokogiri successfully, so I"m able to build native extensions.

Obviously something's different and I just need to track it down, but what it is I've been unable to track it down. Giving up for the time being, but wanted to update based on my findings. I think I've ruled out rvm and where brew is installed as culprits.

Just have to dig deeper into how I've set things up.

```
will update shortly
```

**Comment by blacktm** [comment]
Thanks for the update. Could you try to update Simple 2D to [v0.1.0](https://github.com/simple2d/simple2d/releases/tag/v0.1.0) by running `brew update && brew upgrade simple2d` (you can confirm with `simple2d -v`), then try reinstalling the gem.

I'm also interested to see if Ruby can find the header and lib, which you can test for in IRB. If so, the output should look like this:

```
$ irb
irb(main):001:0> require 'mkmf'
=> true
irb(main):002:0> have_header('simple2d.h')
checking for simple2d.h... yes
=> true
irb(main):003:0> have_library('simple2d')
checking for main() in -lsimple2d... yes
=> true
```

**Comment by EricSlick** [comment]
On my imac, I can find the headers and library, but not on my laptop.

```
21:05:55- $ irb
2.3.0 :001 > require 'mkmf'
 => true 
2.3.0 :002 > have_header('simple2d.h')
checking for simple2d.h... yes
 => true 
2.3.0 :003 > have_library('simple2d')
checking for main() in -lsimple2d... yes
 => true 
```

This fails on my laptop.

This is using simple2d 0.0.4 and brew says that's the latest version, even after brew update.

I'll check into why I'm not getting simple2d 0.1.0 installing.

**Comment by EricSlick** [comment]
Tried it on my laptop.

To get simple2d 0.1.0 installed, I had to manually update the formula (version and SHA) to pull down the right version and then upgrade rather than install. 

simple2d seems to have installed correctly but I'm still getting the same error when trying to install the ruby2d gem.

```
$ simple2d -v
0.1.0

$ brew upgrade simple2d
==> Upgrading 1 outdated package, with result:
simple2d/tap/simple2d 0.1.0
==> Upgrading simple2d/tap/simple2d
==> Downloading https://github.com/simple2d/simple2d/archive/v0.1.0.tar.gz
Already downloaded: /Library/Caches/Homebrew/simple2d-0.1.0.tar.gz
==> make
==> make install PREFIX=/usr/local/Cellar/simple2d/0.1.0
🍺  /usr/local/Cellar/simple2d/0.1.0: 6 files, 66.2K, built in 1 second


$ simple2d -v
0.1.0


$ bundle
Resolving dependencies...
Using rake 10.4.2
Using bundler 1.11.2
Using coderay 1.1.0
Using diff-lcs 1.2.5
Using gosu 0.10.4
Using method_source 0.8.2
Using slop 3.6.0
Using rspec-support 3.4.1
Using gol2 0.1.0 from source at `.`
Using pry 0.10.3
Using rspec-core 3.4.1
Using rspec-expectations 3.4.0
Using rspec-mocks 3.4.0
Using rspec 3.4.0
Bundle complete! 5 Gemfile dependencies, 14 gems now installed.
Use `bundle show [gemname]` to see where a bundled gem is installed.

~/workspace/interview_tests/gol2 [master*]
$ gem install ruby2d
Building native extensions.  This could take a while...
ERROR:  Error installing ruby2d:
	ERROR: Failed to build gem native extension.

    current directory: /Users/ericslick/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/ruby2d-0.2.0/ext/ruby2d
/Users/ericslick/.rbenv/versions/2.3.0/bin/ruby -r ./siteconf20160126-1421-hi4hju.rb extconf.rb
Cloning into '/usr/local/Library/Taps/simple2d/homebrew-tap'...
Error: simple2d/tap/simple2d 0.1.0 already installed
creating Makefile

current directory: /Users/ericslick/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/ruby2d-0.2.0/ext/ruby2d
make "DESTDIR=" clean

current directory: /Users/ericslick/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/ruby2d-0.2.0/ext/ruby2d
make "DESTDIR="
compiling ruby2d.c
ruby2d.c:2:10: fatal error: 'simple2d.h' file not found
#include <simple2d.h>
         ^
1 error generated.
make: *** [ruby2d.o] Error 1

make failed, exit code 2

Gem files will remain installed in /Users/ericslick/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/ruby2d-0.2.0 for inspection.
Results logged to /Users/ericslick/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/extensions/x86_64-darwin-15/2.3.0-static/ruby2d-0.2.0/gem_make.out
```

and checking if the libraries are installed...
``` 
$ irb
irb(main):001:0> require 'mkmf'
=> true
irb(main):002:0> have_header('simple2d.h')
checking for simple2d.h... no
=> false
irb(main):003:0> have_library('simple2d')
checking for main() in -lsimple2d... no
=> false
irb(main):004:0> 
```

**Comment by EricSlick** [comment]
Figured it out.  

```xcode-select --install```

I thought this was already installed, but I'd looked at my include paths...

cpp -v

and saw that usr/local/include was not listed.  Searching for answers on how to ensure that it's included, I finally just ran the command above and was shocked that the tools weren't installed.  I thought they were installed automatically by xcode these days, but I guess not or it works differently than I expected.

My bad. I am able to install the gem now. I was a simple path problem on my end, but as usual, a simple problem with a long search for the "DOH!" moment.

**Comment by blacktm** [comment]
Awesome, glad you figured it out! You might have actually already had the Xcode command-line tools installed – I think major updates to Xcode actually reset the developer environment and re-lock down directories, until you agree to the new license terms and so forth. (I remember trying to use `cc` one time and the Xcode dialog popping up automatically.) Not a great user experience there, APPLE!

I actually wonder if `brew doctor` would have caught it 🤔

**Comment by EricSlick** [comment]
I could have missed it I suppose, but I'm 99.99% sure ```brew doctor``` didn't catch it. It would be a good one for it to catch, though.

I'll have to watch for this next time I upgrade xcode.

**Comment by rhpo** [comment]
What if a not a macOS user? (Windows)
